[package]
name = "sokoban-sokoban"
version = "0.2.0"
authors = ["TLovell <trevorlovelldesign@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
hot = []

[dependencies]
bevy = {version = "0.7", features = ["wav"]}
bevy_easings = "0.7"
bevy_ecs_ldtk = "0.3"
rand = "0.8"

[target.wasm32-unknown-unknown.dependencies]
bevy_ecs_ldtk = { version = "0.3", features = ["atlas"] }
