[package]
name = "willos-graveyard"
version = "0.8.0"
authors = ["TLovell <trevorlovelldesign@gmail.com>"]
edition = "2021"

[features]
# For release builds, make sure to use --no-default-features
default = ["hot", "fast-compile"]
dev = ["inspector"]

hot = []
fast-compile = ["bevy/dynamic_linking"]
inspector = ["bevy-inspector-egui"]

[dependencies]
bevy = { version = "0.10", features = ["wav"] }
bevy_easings = "0.10"
bevy_ecs_ldtk = { git = "https://github.com/trouv/bevy_ecs_ldtk", branch = "main" }
rand = "0.8"
serde = "1"
serde_json = "1"
bevy_asset_loader = { version = "0.15", features = ["2d"] }
bevy-inspector-egui = { version = "0.18", optional = true }
thiserror = "1"
leafwing-input-manager = "0.9"

[target.wasm32-unknown-unknown.dependencies]
bevy_ecs_ldtk = { git = "https://github.com/trouv/bevy_ecs_ldtk", branch = "main", features = ["atlas"] }

[patch.crates-io]
bevy_ecs_tilemap = { version = "0.9", git = "https://github.com/geieredgar/bevy_ecs_tilemap", branch = "bevy_track" }
