name: Version

# The goal is to have this run at midnight in Denver
# This requires us to use two crons due to daylight savings
on:
  schedule:
    - cron: '0 7 * 1,2,11,12 *'
    - cron: '0 6 * 3,4,5,6,7,8,9,10 *'
  workflow_dispatch:

jobs:
  version:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      # This job only has one step since it all needs to be wrapped in an if statement
      - name: Update version
        run: |
          git fetch --tags
          LAST_TAG=$(git tag | head -n 1)
          CHANGED_ASSETS=$(git diff --name-only $LAST_TAG -- assets/)
          CHANGED_CODE=$(git diff --name-only $LAST_TAG -- src/ Cargo.*)
          if [[ $CHANGED_ASSETS || $CHANGED_CODE ]]; then
            echo "changes made, updating version"

            if [[ $LAST_TAG =~ ^v\?([0-9]+)\.([0-9]+)\.([0-9]+).*$ ]]; then
              CODE_VERSION_MAJOR=${BASH_REMATCH[1]}
              CODE_VERSION_MINOR=${BASH_REMATCH[2]}
              CODE_VERSION_PATCH=${BASH_REMATCH[3]}

              UPDATE_CARGO=0
              MAJOR_COMMITS=$(git log $LAST_TAG..HEAD --grep '^\w+!:')
              if [[ $MAJOR_COMMITS ]]; then
                echo "incrementing code version (minor)"
                CODE_VERSION_MINOR=$(( $CODE_VERSION_MINOR + 1 ))
                UPDATE_CARGO=1
              elif [[ $CHANGED_CODE ]]; then
                echo "incrementing code version (patch)"
                CODE_VERSION_PATCH=$(( $CODE_VERSION_PATCH + 1 ))
                UPDATE_CARGO=1
              fi
              CODE_VERSION="$CODE_VERSION_MAJOR.$CODE_VERSION_MINOR.$CODE_VERSION_PATCH"

              git config user.name 'github-actions[bot]'
              git config user.email 'github-actions[bot]@users.noreply.github.com'
              if [[ $UPDATE_CARGO ]]; then
                echo "updating cargo"
                sed "s/^version = \".*\"$/version = \"$CODE_VERSION\"/" Cargo.toml -i
                cargo update
                git add Cargo.*
                git commit -m "build: increment version to $CODE_VERSION, update dependencies"
              fi

              DATE_VERSION=$(date +%y.%m.%d)
              VERSION="v$CODE_VERSION-$DATE_VERSION"
              COLLISION=0
              while [[ $(git tag | grep $VERSION) ]]; do
                COLLISION=$(( $COLLISION + 1 ))
                VERSION="v$CODE_VERSION-$DATE_VERSION-$COLLISION"
              done

              echo "new version: $VERSION"

              echo "creating tag, pushing"
              git tag -a $VERSION -m "version updated to $VERSION by CI"
              git push --follow-tags
            else
              echo "most recent tag isn't semver, skipping.."
            fi
          else
            echo "no changes detected, skipping.."
          fi
